pipeline {

 agent any
 environment {
     NEW_VERSION = '1.3.2'
     SERVER_CRED = credentials('github101')
 }

 stages {
   
    stage("Git") {
      steps {
        echo 'Get the application from Git'
        echo "Building New Versio ${NEW_VERSION}"
      }
    }


    stage("build") {
      when {
          expression {
              env.BRANCH_NAME == 'master'
          }
      }
      steps {
        echo 'Building the application'
        echo 'Compiling the Application'
        echo "Credentials -  ${SERVER_CRED}"
      }
    }

 }
 
 post {
    always {
      //
    }
    
    success {
        //
    }
    failure {
        //     
    }
    
 
 }


}